[project]
name = "my-app"
version = "0.1.0"
dependencies = [
    "Flask==2.2.0",
    "numpy==1.24.3",
]

[build-system]
requires = ["setuptools>=70.0.0", "wheel"]
build-backend = "setuptools.build_meta"
